name: ryu-cho

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # on button click

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ github.token }}
          username: github-actions
          email: "action@github.com"

          upstream-repo: https://github.com/mostafa-nematpour/vite-docs-fa.git
          upstream-repo-branch: main

          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: 1a2e5e6d9a6bb2531bf73be801c9778dbf39d51b
          path-starts-with: docs/
          workflow-name: ryu-cho
